
variables:
  ORD_SOUMET_CPUS: "20"
  ORD_SOUMET_CM: "20G"
  ORD_SOUMET_TMPFS: "10G"
  JOB_CPUS: "10"
  doc_install_dir: "/home/spst900/public_html/fstpy/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}"
  latest_doc_install_dir: "/home/spst900/public_html/fstpy/latest"
    

stages:
  - run_unittest
  - run_regtests
  - make_doc
  - install_doc
  - ssm_package


# default:
# when 'default' becomes supported, uncomment the above line, delete this line, and indent the before_script part.
before_script:
  - export ORDENV_SITE_PROFILE=20200724
  - export ORDENV_COMM_PROFILE=eccc/20200724
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.3
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh
  - export EC_ATOMIC_PROFILE_VERSION=1.12.0
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/migdep/5.1.1 eccc/mrd/rpn/MIG/ENV/rpnpy/2.1.2
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/python_packages/python3.6/all/2021.07
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmdw/PRIVATE/dev_python_packages/python3.6/all/2021.07
  # - .  "/fs/ssm/eccc/cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64/etc/profile.d/conda.sh"
  # - export PATH="/fs/ssm/eccc/cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64/bin:$PATH"
  # - export CONDA_PREFIX=/home/sbf000/.conda/envs/${CONDA_ENV}
  # - export PROJ_LIB=/home/sbf000/.conda/envs/${CONDA_ENV}/share/proj
  # - export PATH=/home/sbf000/.conda/envs/${CONDA_ENV}/bin:$PATH

run_unittest: 
  stage: run_unittest 
  script:
    - cd test    
    - python3 -m pytest -v -m unit_tests 
    

run_regtests:
  stage: run_regtests
  script:
    - cd test
    - python3 -m pytest -v -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make doc
  artifacts:
    paths:
      - doc/_build/html 

      
install_doc:
  stage: install_doc
  script:
    - echo "CI_DEFAULT_BRANCH = ${CI_DEFAULT_BRANCH}"
    - echo "CI_COMMIT_BRANCH = ${CI_COMMIT_BRANCH}"
    - echo "CI_BUILD_REF_NAME = ${CI_BUILD_REF_NAME}"
    - echo "CI_PIPELINE_ID = ${CI_PIPELINE_ID}"
    - cd doc/_build/html
    - cdir=`pwd`
    - mkdir -p ${doc_install_dir}
    - cp -r ${cdir}/* ${doc_install_dir}
    - echo "Installed in ${doc_install_dir}"

ssm_package:
  stage: ssm_package
  script:
    - cd misc/ssm
    - ./make_package.sh






