
variables:
  ORD_SOUMET_CPUS: "20"
  ORD_SOUMET_CM: "20G"
  ORD_SOUMET_TMPFS: "10G"
    

stages:
  - run_unittest
  - run_regtests
  - make_doc
  - ssm_package
  - install_doc


# default:
# when 'default' becomes supported, uncomment the above line, delete this line, and indent the before_script part.
before_script:
  - set +e
  - export ORDENV_SITE_PROFILE=20200724
  - export ORDENV_COMM_PROFILE=eccc/20200724
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.3
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh
  - export EC_ATOMIC_PROFILE_VERSION=1.12.0
  - . /fs/ssm/eccc/mrd/ordenv/profile/check_profile_1.0.0
  - set -e
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/migdep/5.1.1 eccc/mrd/rpn/MIG/ENV/rpnpy/2.1.2
  - . ssmuse-sh -x cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64
  - .  "/fs/ssm/eccc/cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64/etc/profile.d/conda.sh"
  - export PATH="/fs/ssm/eccc/cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64/bin:$PATH"
  


run_unittest:
  stage: run_unittest
  script:
    - source activate fstpy_jupyter_env
    - cd test    
    - /home/sbf000/.conda/envs/fstpy_jupyter_env/bin/python -m pytest -m unit_tests 
    

run_regtests:
  stage: run_regtests
  script:
    - cd test
    - /home/sbf000/.conda/envs/fstpy_jupyter_env/bin/python -m pytest -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make clean
    - make html
  artifacts:
    paths:
      - doc/_build/html

ssm_package:
  stage: ssm_package
  script:
    - cd misc/ssm
    - ./make_package.sh

install_doc:
  stage: install_doc
  script:
    - cd doc/_build/html
    - rm -rf ~sbf000/public_html/fstpy/latest/*
    - cp -r * ~sbf000/public_html/fstpy/latest/.





