{% set name = load_setup_py_data()['name'] %}
{% set version = load_setup_py_data()['version'] %}
{% set url = load_setup_py_data()['url'] %}
{% set summary = load_setup_py_data()['description'] %}


package:
  name: {{ name|lower }}
  version: {{ version }}


build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0
    - fortiers::eccc_rpnpy >=2.2.0rc3
    - fortiers::cmcdict >=2024.07.22

  run:
    - python
    - pandas >=1.2.4
    - numpy >=1.19.5
    - dask >=2021.8.0
    - fortiers::eccc_rpnpy >=2.2.0rc3
    - fortiers::cmcdict >=2024.07.22


test:
  imports:
    - {{ name|lower }}

about:
  home: {{ url }}
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: {{ summary }}

source:
  path: ../
